Repository brandmooffin/cocos2d-mono, pull requests merged in 2024-10, with the labels that each got.

#407 under unknown circumstances new index could be out of range, causing …
  cocos2d/sprite_nodes/CCSpriteBatchNode.cs
Labels: bug

#408 update(audio): pause & resume all sfx
  cocos2d/denshion/CCSimpleAudioEngine.cs
Labels: enhancement

#409 update(actions): streamline actions and menu align functions
  cocos2d/base_nodes/CCNode.cs
  cocos2d/extentions/GUI/CCControlExtension/CCControlButton.cs
  cocos2d/menu_nodes/CCMenu.cs
  cocos2d/menu_nodes/CCMenuItemLabel.cs
  cocos2d/menu_nodes/CCMenuItemSprite.cs
  cocos2d/menu_nodes/CCMenuItemToggle.cs
Labels: enhancement

#413 We want to add possibility to set atlas texture size with static meth…
  cocos2d/base_nodes/CCNode.cs
  cocos2d/label_nodes/CCLabel.cs
Labels: bug

#415 Release/2.4.8.1
  Nuget Packages/Cocos2D.Android.nuspec
  Nuget Packages/Cocos2D.Core.Android.nuspec
  Nuget Packages/Cocos2D.Core.DesktopGL.nuspec
  Nuget Packages/Cocos2D.Core.Uwp.nuspec
  Nuget Packages/Cocos2D.Core.Windows.nuspec
  Nuget Packages/Cocos2D.Core.iOS.nuspec
  Nuget Packages/Cocos2D.DesktopGL.nuspec
  Nuget Packages/Cocos2D.Uwp.nuspec
  Nuget Packages/Cocos2D.Windows.nuspec
  Nuget Packages/Cocos2D.iOS.nuspec
  box2d/box2d.Android/box2d.Android.csproj
  box2d/box2d.DesktopGL/box2d.DesktopGL.csproj
  box2d/box2d.Uwp/Properties/AssemblyInfo.cs
  box2d/box2d.Windows/box2d.Windows.csproj
  box2d/box2d.iOS/box2d.iOS.csproj
  cocos2d/base_nodes/CCNode.cs
  cocos2d/cocos2d.Android/cocos2d.Android.csproj
  cocos2d/cocos2d.Core.Android/cocos2d.Core.Android.csproj
  cocos2d/cocos2d.Core.DesktopGL/cocos2d.Core.DesktopGL.csproj
  cocos2d/cocos2d.Core.Uwp/Cocos2D.Core.Uwp.nuspec
  cocos2d/cocos2d.Core.Uwp/Properties/AssemblyInfo.cs
  cocos2d/cocos2d.Core.Windows/cocos2d.Core.Windows.csproj
  cocos2d/cocos2d.Core.iOS/cocos2d.Core.iOS.csproj
  cocos2d/cocos2d.DesktopGL/cocos2d.DesktopGL.csproj
  cocos2d/cocos2d.Uwp/Cocos2D.Uwp.nuspec
  cocos2d/cocos2d.Uwp/Properties/AssemblyInfo.cs
  cocos2d/cocos2d.Windows/cocos2d.Windows.csproj
  cocos2d/cocos2d.iOS/cocos2d.iOS.csproj
  cocos2d/label_nodes/CCLabel.cs
Labels: release
