Repository brandmooffin/cocos2d-mono, pull requests merged in 2024-08, with the labels that each got.

#378 lower ios target version
  box2d/box2d.iOS/box2d.iOS.csproj
  cocos2d/cocos2d.Core.iOS/cocos2d.Core.iOS.csproj
  cocos2d/cocos2d.iOS/cocos2d.iOS.csproj
Labels: dependencies

#379 Release/2.4.7.13
  Nuget Packages/Cocos2D.Android.nuspec
  Nuget Packages/Cocos2D.Core.Android.nuspec
  Nuget Packages/Cocos2D.Core.DesktopGL.nuspec
  Nuget Packages/Cocos2D.Core.Uwp.nuspec
  Nuget Packages/Cocos2D.Core.Windows.nuspec
  Nuget Packages/Cocos2D.Core.iOS.nuspec
  Nuget Packages/Cocos2D.DesktopGL.nuspec
  Nuget Packages/Cocos2D.Uwp.nuspec
  Nuget Packages/Cocos2D.Windows.nuspec
  Nuget Packages/Cocos2D.iOS.nuspec
  Samples/Android/Cocos2dMonoGame.Android/Cocos2dMonoGame.Android.csproj
  Samples/AppGame/AppGame.Android/AppGame.Android.csproj
  Samples/AppGame/AppGame.iOS.CoreApp/AppGame.iOS.CoreApp.csproj
  Samples/AppGame/AppGame.iOS/AppGame.iOS.csproj
  Samples/Core.Android/Cocos2dMonoGame.Core.Android/Cocos2dMonoGame.Core.Android.csproj
  Samples/Core.DesktopGL/Cocos2DMonoGame.Core.DesktopGL/Cocos2DMonoGame.Core.DesktopGL.csproj
  Samples/Core.Uwp/Cocos2dMonoGame.Core.Uwp/Cocos2dMonoGame.Core.Uwp.csproj
  Samples/Core.Windows/Cocos2dMonoGame.Core.Windows/Cocos2DMonoGame.Core.Windows.csproj
  Samples/Core.iOS/Cocos2dMonoGame.Core.iOS/Cocos2DMonoGame.Core.iOS.csproj
  Samples/DesktopGL/Cocos2DMonoGame.DesktopGL/Cocos2DMonoGame.DesktopGL.csproj
  Samples/TetrisGame/TetrisGame.Android/TetrisGame.Android.csproj
  Samples/TetrisGame/TetrisGame.DesktopGL/TetrisGame.DesktopGL.csproj
  Samples/Uwp/Cocos2dMonoGame.Uwp/Cocos2dMonoGame.Uwp.csproj
  Samples/Windows/Cocos2dMonoGame.Windows/Cocos2dMonoGame.Windows.csproj
  Samples/iOS/Cocos2dMonoGame.iOS/Cocos2dMonoGame.iOS.csproj
  box2d/box2d.Android/box2d.Android.csproj
  box2d/box2d.DesktopGL/box2d.DesktopGL.csproj
  box2d/box2d.Uwp/Properties/AssemblyInfo.cs
  box2d/box2d.Windows/box2d.Windows.csproj
  box2d/box2d.iOS/box2d.iOS.csproj
  cocos2d/cocos2d.Android/cocos2d.Android.csproj
  cocos2d/cocos2d.Core.Android/cocos2d.Core.Android.csproj
  cocos2d/cocos2d.Core.DesktopGL/cocos2d.Core.DesktopGL.csproj
  cocos2d/cocos2d.Core.Uwp/Properties/AssemblyInfo.cs
  cocos2d/cocos2d.Core.Windows/cocos2d.Core.Windows.csproj
  cocos2d/cocos2d.Core.iOS/cocos2d.Core.iOS.csproj
  cocos2d/cocos2d.DesktopGL/cocos2d.DesktopGL.csproj
  cocos2d/cocos2d.Uwp/Properties/AssemblyInfo.cs
  cocos2d/cocos2d.Windows/cocos2d.Windows.csproj
  cocos2d/cocos2d.iOS/cocos2d.iOS.csproj
Labels: release

#380 update font config when font size changes
  cocos2d/label_nodes/CCLabel.cs
Labels: bug

#382 Release/2.4.7.14
  Nuget Packages/Cocos2D.Android.nuspec
  Nuget Packages/Cocos2D.Core.Android.nuspec
  Nuget Packages/Cocos2D.Core.DesktopGL.nuspec
  Nuget Packages/Cocos2D.Core.Uwp.nuspec
  Nuget Packages/Cocos2D.Core.Windows.nuspec
  Nuget Packages/Cocos2D.Core.iOS.nuspec
  Nuget Packages/Cocos2D.DesktopGL.nuspec
  Nuget Packages/Cocos2D.Uwp.nuspec
  Nuget Packages/Cocos2D.Windows.nuspec
  Nuget Packages/Cocos2D.iOS.nuspec
  Samples/Android/Cocos2dMonoGame.Android/Cocos2dMonoGame.Android.csproj
  Samples/AppGame/AppGame.Android/AppGame.Android.csproj
  Samples/AppGame/AppGame.iOS.CoreApp/AppGame.iOS.CoreApp.csproj
  Samples/AppGame/AppGame.iOS/AppGame.iOS.csproj
  Samples/Core.Android/Cocos2dMonoGame.Core.Android/Cocos2dMonoGame.Core.Android.csproj
  Samples/Core.DesktopGL/Cocos2DMonoGame.Core.DesktopGL/Cocos2DMonoGame.Core.DesktopGL.csproj
  Samples/Core.Uwp/Cocos2dMonoGame.Core.Uwp/Cocos2dMonoGame.Core.Uwp.csproj
  Samples/Core.Windows/Cocos2dMonoGame.Core.Windows/Cocos2DMonoGame.Core.Windows.csproj
  Samples/Core.iOS/Cocos2dMonoGame.Core.iOS/Cocos2DMonoGame.Core.iOS.csproj
  Samples/DesktopGL/Cocos2DMonoGame.DesktopGL/Cocos2DMonoGame.DesktopGL.csproj
  Samples/TetrisGame/TetrisGame.Android/TetrisGame.Android.csproj
  Samples/TetrisGame/TetrisGame.DesktopGL/TetrisGame.DesktopGL.csproj
  Samples/Uwp/Cocos2dMonoGame.Uwp/Cocos2dMonoGame.Uwp.csproj
  Samples/Windows/Cocos2dMonoGame.Windows/Cocos2dMonoGame.Windows.csproj
  Samples/iOS/Cocos2dMonoGame.iOS/Cocos2dMonoGame.iOS.csproj
  box2d/box2d.Android/box2d.Android.csproj
  box2d/box2d.DesktopGL/box2d.DesktopGL.csproj
  box2d/box2d.Uwp/Properties/AssemblyInfo.cs
  box2d/box2d.Windows/box2d.Windows.csproj
  box2d/box2d.iOS/box2d.iOS.csproj
  cocos2d/cocos2d.Android/cocos2d.Android.csproj
  cocos2d/cocos2d.Core.Android/cocos2d.Core.Android.csproj
  cocos2d/cocos2d.Core.DesktopGL/cocos2d.Core.DesktopGL.csproj
  cocos2d/cocos2d.Core.Uwp/Properties/AssemblyInfo.cs
  cocos2d/cocos2d.Core.Windows/cocos2d.Core.Windows.csproj
  cocos2d/cocos2d.Core.iOS/cocos2d.Core.iOS.csproj
  cocos2d/cocos2d.DesktopGL/cocos2d.DesktopGL.csproj
  cocos2d/cocos2d.Uwp/Properties/AssemblyInfo.cs
  cocos2d/cocos2d.Windows/cocos2d.Windows.csproj
  cocos2d/cocos2d.iOS/cocos2d.iOS.csproj
  cocos2d/label_nodes/CCLabel.cs
Labels: release

#383 fix the vertical alignment of all text on android
  cocos2d/label_nodes/CCLabel-Android.cs
Labels: bug

#385 Android: clean-up static context for CCLabel and re-initialize TTFAtl…
  cocos2d/label_nodes/CCLabel.cs
  cocos2d/label_nodes/CCLabelBMFont.cs
Labels: bug

#386 Release/2.4.7.16
  Nuget Packages/Cocos2D.Android.nuspec
  Nuget Packages/Cocos2D.Core.Android.nuspec
  Nuget Packages/Cocos2D.Core.DesktopGL.nuspec
  Nuget Packages/Cocos2D.Core.Uwp.nuspec
  Nuget Packages/Cocos2D.Core.Windows.nuspec
  Nuget Packages/Cocos2D.Core.iOS.nuspec
  Nuget Packages/Cocos2D.DesktopGL.nuspec
  Nuget Packages/Cocos2D.Uwp.nuspec
  Nuget Packages/Cocos2D.Windows.nuspec
  Nuget Packages/Cocos2D.iOS.nuspec
  Samples/Android/Cocos2dMonoGame.Android/Cocos2dMonoGame.Android.csproj
  Samples/AppGame/AppGame.Android/AppGame.Android.csproj
  Samples/AppGame/AppGame.iOS.CoreApp/AppGame.iOS.CoreApp.csproj
  Samples/AppGame/AppGame.iOS/AppGame.iOS.csproj
  Samples/Core.Android/Cocos2dMonoGame.Core.Android/Cocos2dMonoGame.Core.Android.csproj
  Samples/Core.DesktopGL/Cocos2DMonoGame.Core.DesktopGL/Cocos2DMonoGame.Core.DesktopGL.csproj
  Samples/Core.Uwp/Cocos2dMonoGame.Core.Uwp/Cocos2dMonoGame.Core.Uwp.csproj
  Samples/Core.Windows/Cocos2dMonoGame.Core.Windows/Cocos2DMonoGame.Core.Windows.csproj
  Samples/Core.iOS/Cocos2dMonoGame.Core.iOS/Cocos2DMonoGame.Core.iOS.csproj
  Samples/DesktopGL/Cocos2DMonoGame.DesktopGL/Cocos2DMonoGame.DesktopGL.csproj
  Samples/TetrisGame/TetrisGame.Android/TetrisGame.Android.csproj
  Samples/TetrisGame/TetrisGame.DesktopGL/TetrisGame.DesktopGL.csproj
  Samples/Uwp/Cocos2dMonoGame.Uwp/Cocos2dMonoGame.Uwp.csproj
  Samples/Windows/Cocos2dMonoGame.Windows/Cocos2dMonoGame.Windows.csproj
  Samples/iOS/Cocos2dMonoGame.iOS/Cocos2dMonoGame.iOS.csproj
  box2d/box2d.Android/box2d.Android.csproj
  box2d/box2d.DesktopGL/box2d.DesktopGL.csproj
  box2d/box2d.Uwp/Properties/AssemblyInfo.cs
  box2d/box2d.Windows/box2d.Windows.csproj
  box2d/box2d.iOS/box2d.iOS.csproj
  cocos2d/cocos2d.Android/cocos2d.Android.csproj
  cocos2d/cocos2d.Core.Android/cocos2d.Core.Android.csproj
  cocos2d/cocos2d.Core.DesktopGL/cocos2d.Core.DesktopGL.csproj
  cocos2d/cocos2d.Core.Uwp/Cocos2D.Core.Uwp.nuspec
  cocos2d/cocos2d.Core.Uwp/Properties/AssemblyInfo.cs
  cocos2d/cocos2d.Core.Windows/cocos2d.Core.Windows.csproj
  cocos2d/cocos2d.Core.iOS/cocos2d.Core.iOS.csproj
  cocos2d/cocos2d.DesktopGL/cocos2d.DesktopGL.csproj
  cocos2d/cocos2d.Uwp/Cocos2D.Uwp.nuspec
  cocos2d/cocos2d.Uwp/Properties/AssemblyInfo.cs
  cocos2d/cocos2d.Windows/cocos2d.Windows.csproj
  cocos2d/cocos2d.iOS/cocos2d.iOS.csproj
  cocos2d/label_nodes/CCLabel.cs
  cocos2d/label_nodes/CCLabelBMFont.cs
Labels: release
